# Generated by Django 5.0.6 on 2024-06-29 10:29

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_options_alter_users_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
