version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - services-network
    environment:
      DATABASE_URL: mysql://root:root@db:3306/user  

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: user
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - backend-dbdata:/var/lib/mysql 
    ports:
      - 33066:3306
    networks:
      - services-network  

networks:
  services-network:
    external: true

volumes:
  backend-dbdata:  # Define a named volume for the backend db
